/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_java_sample;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * log
     */
    private static final Logger log = LogManager.getLogger(App.class);

    public static void main(String[] args) {
        new EditTemplateClone(
                EditTemplateClone.EXPORT_DIR_PATH + "book.xlsx",
                "newBook.xlsx"
        ).run();
    }
}
